//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinListing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public int PK_ListingID { get; set; }
        public string CoinName { get; set; }
        public string Token { get; set; }
        public string Short_Description { get; set; }
        public string Description { get; set; }
        public string WebSiteLink { get; set; }
        public string Image { get; set; }
        public Nullable<int> FK_StatusID { get; set; }
        public Nullable<int> FK_ProgressID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> PreStartDate { get; set; }
        public Nullable<System.DateTime> PreEndDate { get; set; }
        public string WhitePaper { get; set; }
        public string TotalSupply { get; set; }
        public string SoftCap { get; set; }
        public string HardCap { get; set; }
        public Nullable<int> FK_ListingStageID { get; set; }
        public string VideoLink { get; set; }
        public string Rating { get; set; }
        public string Price { get; set; }
        public string Plaform { get; set; }
        public string BuyWith { get; set; }
        public string TwitterLink { get; set; }
        public string FacebookLink { get; set; }
        public string LinkedInLink { get; set; }
        public string TelegramLink { get; set; }
        public string RedditLink { get; set; }
    
        public virtual ListingStage ListingStage { get; set; }
        public virtual Progress Progress { get; set; }
        public virtual Status Status { get; set; }
    }
}
